"""Pseudospectral quasi-periodic-torus corrector for the CRNBP, N=5 (`#720`).

The "EOM swap" of `#690`'s CCR4BP torus corrector -- again
--------------------------------------------------------------
`#690` built ``search.variational_ccr4bp_torus`` as `#617`'s QBCP torus
corrector with the QBCP RHS/Jacobian swapped for `#689`'s CCR4BP (single
perturber, Ganymede). `#717` then built the N=5 CRNBP core module
(``core.crnbp``: Jupiter-Europa base + TWO simultaneous perturbers, Io and
Ganymede) and proved -- algebraically, numerically, and by an independent
re-derivation -- that the genuinely-new N=5 physics (the pairwise "inner sum"
coupling term between Io and Ganymede) contributes EXACTLY ZERO to both the
total spacecraft acceleration and the variational Jacobian, for any N. So the
N=5 forcing is a straightforward SUPERPOSITION of Io's own direct+indirect
periodic forcing (identical in form to Ganymede's, `#689`'s own established
single-perturber term) plus Ganymede's own -- unchanged. This module is
therefore ANOTHER thin EOM swap: `#690`'s corrector with the single
``(mu_gan, a_gan, gx, gy)`` forcing generalized to a tuple of perturbers, and
the coupling term OMITTED from the algebraic (Fourier-residual) RHS/Jacobian
as a deliberate, PROVEN-exact simplification (see
:func:`_crnbp_rhs_grid`'s docstring) -- not an approximation. The independent
nonlinear closure check (:func:`_independent_closure`) propagates through
:func:`cyclerfinder.core.crnbp.crnbp_eom`, which DOES include the coupling
term faithfully, so if the omission were ever unsafe (it provably is not) the
closure residual would catch it.

``variational_ccr4bp_torus.py`` itself is UNTOUCHED (per the `#689`/`#690`
discipline of never modifying a validated module for a new extension) --
this is a new, separate module, structurally parallel to it.

The `#720` task: mu_Io continuation from the validated N=4 limit
------------------------------------------------------------------
`#714`'s scoping pass found there is NO literature-grade dynamical positive
control for any N=5 CRNBP torus/connection (Gilliam's own thesis explicitly
says periodic-orbit existence in the generic CRNBP is open). The prescribed
control is SELF-GENERATED by continuation: `#690`'s own already-converged,
already-validated Jupiter-Europa 3:4 CCR4BP torus (Kumar et al. 2021 object
class) is EXACTLY this system's ``mu_Io = 0`` endpoint (the N=5 CRNBP reduces
byte-exactly to the N=4 CCR4BP at ``mu_Io = 0`` -- `#717`'s own Gate 1,
``tests/core/test_crnbp.py``). :func:`discover_crnbp_torus_from_ccr4bp_seed`
takes a converged ``CCR4BPTorusVariationalResult`` and re-verifies it as a
``mu_Io = 0`` CRNBP torus (machine-precision-close residual, Tier-0 gate);
:func:`continue_crnbp_torus_mu_io` then walks ``mu_Io`` from 0 to its
Laplace-projected physical value (~4.7e-5, `#717`'s own
``jupiter_europa_io_ganymede_default`` registry value) in small steps,
warm-starting each solve from the previous converged torus -- the same
``continue_ccr4bp_torus_mass`` pattern `#690` already used and validated, one
level up.

State / basis machinery (identical to `#690`, reused verbatim)
----------------------------------------------------------------
State is the planar rotating-frame ``(x, y, vx, vy)`` (``_N_STATE = 4``,
same as CCR4BP -- the CRNBP is likewise planar: all perturbers are coplanar
circular orbiters). ``theta1`` is locked to Ganymede's synodic clock exactly
as in `#690` (``omega1 = period_multiple * |omega_gan|``); Io's phase is a
SLAVED function of the same clock via the exact Laplace-lock ratio
``omega_io = -2 * omega_gan`` already baked into
``core.crnbp.CRNBPPerturber.position`` -- no second free clock, no 3-torus,
exactly as `#714` predicted. The real tensor-product Fourier basis, gauge
rows, and analytic-Jacobian least-squares solve are `#617`'s/`#690`'s
machinery, imported and reused without modification
(:mod:`cyclerfinder.search.variational_qbcp_torus`'s ``_basis_matrices`` /
``_k2_first_harmonic_cols``, and `#690`'s own ``_transverse_amplitude``).

Discipline (`#720`)
--------------------
Build + validate ONLY the N=5 torus corrector and its mu_Io continuation.
No whisker/manifold globalization, no heteroclinic search (later, gated
work per `#714`'s shortlist item 3). The returned torus is OUR computation;
no novelty claim without a passing ``search/literature_check.py`` run, no
catalogue writeback (out of scope for this task -- reported to the
coordinating session instead).
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Literal

import numpy as np
from numpy.typing import NDArray
from scipy.integrate import solve_ivp
from scipy.optimize import least_squares

import cyclerfinder.core.crnbp as crnbp
from cyclerfinder.search.outcome_log import log_outcome
from cyclerfinder.search.variational_ccr4bp_torus import (
    CCR4BPTorusVariationalResult,
    _transverse_amplitude,
)
from cyclerfinder.search.variational_qbcp_torus import _basis_matrices, _k2_first_harmonic_cols

_N_STATE = 4  # planar rotating-frame state: x, y, vx, vy (identical to CCR4BP)

# A "perturber grid" tuple: (mu_j, a_j, gx_j, gy_j) with gx_j/gy_j shape (m1,)
# -- this perturber's synodic-frame position sampled at every theta1 grid
# value, mass folded in for a cheap mu_j == 0 skip.
_PerturberGrid = tuple[float, float, NDArray[np.float64], NDArray[np.float64]]


@dataclass(frozen=True)
class CRNBPTorusVariationalResult:
    """An N=5 CRNBP quasi-periodic 2-torus found by 2D pseudospectral collocation.

    Mirrors :class:`cyclerfinder.search.variational_ccr4bp_torus.CCR4BPTorusVariationalResult`
    field-for-field, with ``system`` typed as :class:`cyclerfinder.core.crnbp.CRNBPSystem`
    (two perturbers -- Io, Ganymede -- instead of one).
    """

    system: crnbp.CRNBPSystem
    coeffs: NDArray[np.float64]
    omega1: float
    omega2: float
    rotation_number: float
    rho_strob: float
    period: float
    n1: int
    n2: int
    m1: int
    m2: int
    period_multiple: int
    transverse_amplitude: float
    residual_rms: float
    closure_residual: float
    converged: bool
    n_iter: int
    notes: str = ""
    extras: dict[str, float] = field(default_factory=dict)


def evaluate_torus_state(
    result: CRNBPTorusVariationalResult,
    theta1: float | NDArray[np.float64],
    theta2: float | NDArray[np.float64],
) -> NDArray[np.float64]:
    """Evaluate the 2D Fourier torus state ``u(theta1, theta2)`` (4-vector).

    Identical algorithm to `#690`'s ``evaluate_torus_state`` (duplicated, not
    imported, only because it is typed against this module's own result
    dataclass).
    """
    t1 = np.atleast_1d(np.asarray(theta1, dtype=np.float64))
    t2 = np.atleast_1d(np.asarray(theta2, dtype=np.float64))
    p1, _ = _basis_matrices(result.n1, t1)
    p2, _ = _basis_matrices(result.n2, t2)
    out = np.empty((t1.size, _N_STATE))
    for c in range(_N_STATE):
        full = p1 @ result.coeffs[c] @ p2.T
        out[:, c] = np.diagonal(full) if t1.size == t2.size else full[:, 0]
    if np.isscalar(theta1) and np.isscalar(theta2):
        return np.asarray(out[0], dtype=np.float64)
    return out


# ---------------------------------------------------------------------------
# Pack / unpack (identical to the CCR4BP corrector).
# ---------------------------------------------------------------------------


def _pack(coeffs: NDArray[np.float64], omega2: float) -> NDArray[np.float64]:
    return np.concatenate([coeffs.reshape(-1), [omega2]])


def _unpack(z: NDArray[np.float64], n1: int, n2: int) -> tuple[NDArray[np.float64], float]:
    n_coef = _N_STATE * (2 * n1 + 1) * (2 * n2 + 1)
    coeffs = z[:n_coef].reshape(_N_STATE, 2 * n1 + 1, 2 * n2 + 1)
    return coeffs, float(z[-1])


# ---------------------------------------------------------------------------
# Perturber phase sampling, vectorized CRNBP RHS, and its state-Jacobian.
# ---------------------------------------------------------------------------


def _perturber_on_theta1(
    perturber: crnbp.CRNBPPerturber, theta1: NDArray[np.float64], omega1: float
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """This perturber's synodic-frame ``(gx, gy)`` position at each ``theta1``.

    ``theta1`` locks to the (Ganymede) clock via ``t = theta1 / omega1``
    (same convention as `#690`'s ``_ganymede_on_theta1``); each perturber's
    OWN phase then advances at its own rate from that shared absolute time,
    ``theta_j(t) = theta0_j + omega_j * t`` -- exactly
    :meth:`cyclerfinder.core.crnbp.CRNBPPerturber.position`, vectorized. For
    Io this automatically reproduces the exact Laplace-lock slaving
    (``omega_io = -2 * omega_gan``) baked into the perturber's own ``omega``
    field -- no separate slaving formula needed here.
    """
    t = theta1 / omega1
    theta = perturber.theta0 + perturber.omega * t
    return perturber.a * np.cos(theta), perturber.a * np.sin(theta)


def _perturber_grids(
    system: crnbp.CRNBPSystem, theta1: NDArray[np.float64], omega1: float
) -> tuple[_PerturberGrid, ...]:
    return tuple((p.mu, p.a, *_perturber_on_theta1(p, theta1, omega1)) for p in system.perturbers)


def _crnbp_rhs_grid(
    u: NDArray[np.float64],
    mu: float,
    perturbers: tuple[_PerturberGrid, ...],
) -> NDArray[np.float64]:
    """Vectorized planar CRNBP RHS on the grid: ``u`` shape ``(4, m1, m2)`` ->
    ``(4, m1, m2)``.

    Base CR3BP pseudo-potential gradient + Coriolis, PLUS each perturber's own
    direct + indirect term (`#690`'s single-perturber formula, summed over
    ``perturbers``). The mutual Io-Ganymede COUPLING term (`#717`'s Eq. 11
    inner sum) is deliberately OMITTED here: `#717` proved algebraically,
    numerically, and by an independent re-derivation that it contributes
    EXACTLY ZERO to the total spacecraft acceleration for any N (an exact
    antisymmetric pairwise cancellation, not an approximation) -- see
    ``core.crnbp``'s module docstring and
    ``tests/core/test_crnbp.py::test_coupling_term_net_contribution_is_exactly_zero``.
    So this vectorized RHS reduces to :func:`cyclerfinder.core.crnbp.crnbp_eom`
    EXACTLY (not approximately) at every grid point -- checked pointwise in
    ``tests/search/test_variational_crnbp_torus.py`` against the FULL
    coupling-included ``crnbp_eom``, which is the sharpest possible structural
    confirmation that the omission is safe.
    """
    x, y, vx, vy = u[0], u[1], u[2], u[3]
    r1c = ((x + mu) ** 2 + y * y) ** 1.5
    r2c = ((x - 1.0 + mu) ** 2 + y * y) ** 1.5
    om1 = 1.0 - mu
    ax = x + 2.0 * vy - om1 * (x + mu) / r1c - mu * (x - 1.0 + mu) / r2c
    ay = y - 2.0 * vx - om1 * y / r1c - mu * y / r2c
    for mu_j, a_j, gxj, gyj in perturbers:
        if mu_j == 0.0:
            continue
        gxb, gyb = gxj[:, None], gyj[:, None]
        dxg = x - gxb
        dyg = y - gyb
        dg3 = (dxg * dxg + dyg * dyg) ** 1.5
        a_j3 = a_j**3
        ax = ax - mu_j * dxg / dg3 - mu_j * gxb / a_j3
        ay = ay - mu_j * dyg / dg3 - mu_j * gyb / a_j3
    return np.stack([vx, vy, ax, ay], axis=0)


def _crnbp_jacobian_grid(
    u: NDArray[np.float64],
    mu: float,
    perturbers: tuple[_PerturberGrid, ...],
) -> NDArray[np.float64]:
    """Vectorized 4x4 state-Jacobian ``dF/du`` at every grid point.

    Base CR3BP Hessian + Coriolis + each perturber's own direct-term Hessian
    block, summed. The coupling term contributes nothing here on TWO
    independent grounds (either alone sufficient): it is spacecraft-state-
    independent (zero derivative, `#717`'s own finding, true term-by-term, not
    just in aggregate), and its total contribution is exactly zero regardless.
    """
    x, y = u[0], u[1]
    r1c = ((x + mu) ** 2 + y * y) ** 1.5
    r2c = ((x - 1.0 + mu) ** 2 + y * y) ** 1.5
    r1f = ((x + mu) ** 2 + y * y) ** 2.5
    r2f = ((x - 1.0 + mu) ** 2 + y * y) ** 2.5
    om1 = 1.0 - mu
    uxx = (
        1.0
        - om1 / r1c
        - mu / r2c
        + 3.0 * om1 * (x + mu) ** 2 / r1f
        + 3.0 * mu * (x - 1.0 + mu) ** 2 / r2f
    )
    uyy = 1.0 - om1 / r1c - mu / r2c + 3.0 * om1 * y * y / r1f + 3.0 * mu * y * y / r2f
    uxy = 3.0 * om1 * (x + mu) * y / r1f + 3.0 * mu * (x - 1.0 + mu) * y / r2f

    for mu_j, _a_j, gxj, gyj in perturbers:
        if mu_j == 0.0:
            continue
        gxb, gyb = gxj[:, None], gyj[:, None]
        dxg = x - gxb
        dyg = y - gyb
        dg2 = dxg * dxg + dyg * dyg
        dg3 = dg2**1.5
        dg5 = dg2**2.5
        uxx = uxx - mu_j * (1.0 / dg3 - 3.0 * dxg * dxg / dg5)
        uyy = uyy - mu_j * (1.0 / dg3 - 3.0 * dyg * dyg / dg5)
        uxy = uxy + 3.0 * mu_j * dxg * dyg / dg5

    m1, m2 = x.shape
    jf = np.zeros((_N_STATE, _N_STATE, m1, m2))
    ones = np.ones((m1, m2))
    jf[0, 2] = ones
    jf[1, 3] = ones
    jf[2, 0], jf[2, 1], jf[2, 3] = uxx, uxy, 2.0 * ones
    jf[3, 0], jf[3, 1], jf[3, 2] = uxy, uyy, -2.0 * ones
    return jf


# ---------------------------------------------------------------------------
# Invariance-PDE residual and its analytic Jacobian (no integration).
# ---------------------------------------------------------------------------


def _residual(
    z: NDArray[np.float64],
    omega1: float,
    mu: float,
    perturbers: tuple[_PerturberGrid, ...],
    n1: int,
    n2: int,
    p1: NDArray[np.float64],
    p1d: NDArray[np.float64],
    p2: NDArray[np.float64],
    p2d: NDArray[np.float64],
    phase2_coord: int,
    amplitude_anchor: float,
    gauge_weight: float,
    rho_target: float,
    rho_weight: float,
) -> NDArray[np.float64]:
    """Real residual: CRNBP quasi-periodic invariance PDE on the 2D grid + 3 gauges.

    Structurally identical to `#690`'s ``_residual``, with ``(mu_gan, a_gan,
    gx, gy)`` generalized to the ``perturbers`` tuple.
    """
    coeffs, omega2 = _unpack(z, n1, n2)
    if not np.isfinite(omega2):
        return np.full(p1.shape[0] * p2.shape[0] * _N_STATE + 3, 1e6)

    m1, m2 = p1.shape[0], p2.shape[0]
    u = np.empty((_N_STATE, m1, m2))
    du1 = np.empty((_N_STATE, m1, m2))
    du2 = np.empty((_N_STATE, m1, m2))
    for c in range(_N_STATE):
        cc = coeffs[c]
        u[c] = p1 @ cc @ p2.T
        du1[c] = p1d @ cc @ p2.T
        du2[c] = p1 @ cc @ p2d.T

    rhs = _crnbp_rhs_grid(u, mu, perturbers)
    lhs = omega1 * du1 + omega2 * du2
    pde_res = (lhs - rhs).reshape(-1)

    _, sin1_col_t2 = _k2_first_harmonic_cols(n2)
    phase2 = coeffs[phase2_coord, 0, sin1_col_t2]
    amp = _transverse_amplitude(coeffs, n2)
    gauge = np.array(
        [
            gauge_weight * phase2,
            gauge_weight * (amp - amplitude_anchor),
            rho_weight * (omega2 - rho_target * omega1),
        ]
    )
    return np.concatenate([pde_res, gauge])


def _jacobian(
    z: NDArray[np.float64],
    omega1: float,
    mu: float,
    perturbers: tuple[_PerturberGrid, ...],
    n1: int,
    n2: int,
    p1: NDArray[np.float64],
    p1d: NDArray[np.float64],
    p2: NDArray[np.float64],
    p2d: NDArray[np.float64],
    phase2_coord: int,
    amplitude_anchor: float,
    gauge_weight: float,
    rho_target: float,
    rho_weight: float,
) -> NDArray[np.float64]:
    """Analytic Jacobian of :func:`_residual` (exact; no finite differencing).

    Same block structure as `#690`'s ``_jacobian``.
    """
    coeffs, omega2 = _unpack(z, n1, n2)
    a1n, a2n = 2 * n1 + 1, 2 * n2 + 1
    m1, m2 = p1.shape[0], p2.shape[0]
    n_coef = _N_STATE * a1n * a2n
    n_free = n_coef + 1
    n_pde = _N_STATE * m1 * m2
    jac = np.zeros((n_pde + 3, n_free))

    b_val = np.einsum("ia,jb->ijab", p1, p2)
    b_d1 = np.einsum("ia,jb->ijab", p1d, p2)
    b_d2 = np.einsum("ia,jb->ijab", p1, p2d)
    lhs_basis = (omega1 * b_d1 + omega2 * b_d2).reshape(m1 * m2, a1n * a2n)
    val_basis = b_val.reshape(m1 * m2, a1n * a2n)

    u = np.empty((_N_STATE, m1, m2))
    du2 = np.empty((_N_STATE, m1, m2))
    for c in range(_N_STATE):
        u[c] = p1 @ coeffs[c] @ p2.T
        du2[c] = p1 @ coeffs[c] @ p2d.T
    jf = _crnbp_jacobian_grid(u, mu, perturbers)  # (4,4,m1,m2)

    for c in range(_N_STATE):
        rows = slice(c * m1 * m2, (c + 1) * m1 * m2)
        cols_c = slice(c * a1n * a2n, (c + 1) * a1n * a2n)
        jac[rows, cols_c] = lhs_basis
        for d in range(_N_STATE):
            cols_d = slice(d * a1n * a2n, (d + 1) * a1n * a2n)
            jf_cd = jf[c, d].reshape(m1 * m2)
            jac[rows, cols_d] -= jf_cd[:, None] * val_basis
        jac[rows, n_coef] = du2[c].reshape(m1 * m2)

    cos1_col_t2, sin1_col_t2 = _k2_first_harmonic_cols(n2)

    def _coef_index(c: int, a: int, b: int) -> int:
        return c * a1n * a2n + a * a2n + b

    jac[n_pde + 0, _coef_index(phase2_coord, 0, sin1_col_t2)] = gauge_weight
    amp = _transverse_amplitude(coeffs, n2)
    if amp > 0:
        for c in range(_N_STATE):
            for a in range(a1n):
                jac[n_pde + 1, _coef_index(c, a, cos1_col_t2)] = (
                    gauge_weight * coeffs[c, a, cos1_col_t2] / amp
                )
                jac[n_pde + 1, _coef_index(c, a, sin1_col_t2)] = (
                    gauge_weight * coeffs[c, a, sin1_col_t2] / amp
                )
    jac[n_pde + 2, n_coef] = rho_weight
    return jac


# ---------------------------------------------------------------------------
# The corrector.
# ---------------------------------------------------------------------------


def correct_crnbp_torus_pseudospectral(
    system: crnbp.CRNBPSystem,
    coeffs0: NDArray[np.float64],
    omega2_0: float,
    *,
    n1: int,
    n2: int,
    amplitude_anchor: float,
    period_multiple: int = 1,
    rho_target: float | None = None,
    rho_weight: float = 1.0,
    m1: int | None = None,
    m2: int | None = None,
    tol: float = 1e-6,
    closure_tol: float = 1e-4,
    max_nfev: int = 200,
    gauge_weight: float = 1.0,
    tr_solver: Literal["exact", "lsmr"] = "exact",
    closure_dt_frac: float = 0.02,
    n_closure_samples: int = 12,
    notes: str = "",
) -> CRNBPTorusVariationalResult:
    """Refine a 2D-Fourier planar CRNBP torus guess to zero invariance residual.

    ``system.perturbers`` MUST be ``(io, ganymede)`` in that order (the exact
    convention :func:`cyclerfinder.core.crnbp.jupiter_europa_io_ganymede_default`
    constructs) -- the LAST perturber is the forcing clock (``omega1 =
    period_multiple * |perturbers[-1].omega|``), matching `#690`'s Ganymede
    clock exactly; any earlier perturbers (here, Io) have their phase slaved to
    that same absolute time via their own ``omega``/``theta0``. Everything
    else mirrors
    :func:`cyclerfinder.search.variational_ccr4bp_torus.correct_ccr4bp_torus_pseudospectral`.
    """
    if coeffs0.shape != (_N_STATE, 2 * n1 + 1, 2 * n2 + 1):
        raise ValueError(
            f"coeffs0 shape {coeffs0.shape} != expected {(_N_STATE, 2 * n1 + 1, 2 * n2 + 1)}"
        )
    if period_multiple < 1:
        raise ValueError(f"period_multiple must be >= 1, got {period_multiple}")
    if not system.perturbers:
        raise ValueError("correct_crnbp_torus_pseudospectral requires >= 1 perturber (clock)")
    mu = system.mu
    clock = system.perturbers[-1]
    omega1 = period_multiple * abs(clock.omega)
    period = 2.0 * np.pi / omega1
    if rho_target is None:
        rho_target = omega2_0 / omega1
    m1 = m1 if m1 is not None else 2 * n1 + 3
    m2 = m2 if m2 is not None else 2 * n2 + 3
    t1 = 2 * np.pi * np.arange(m1) / m1
    t2 = 2 * np.pi * np.arange(m2) / m2
    p1, p1d = _basis_matrices(n1, t1)
    p2, p2d = _basis_matrices(n2, t2)
    perturbers_grid = _perturber_grids(system, t1, omega1)

    cos1, sin1 = _k2_first_harmonic_cols(n2)
    trans_by_coord = np.sqrt(np.sum(coeffs0[:, :, cos1] ** 2 + coeffs0[:, :, sin1] ** 2, axis=1))
    phase2_coord = int(np.argmax(trans_by_coord))

    z0 = _pack(coeffs0, omega2_0)
    solver_args = (
        omega1,
        mu,
        perturbers_grid,
        n1,
        n2,
        p1,
        p1d,
        p2,
        p2d,
        phase2_coord,
        amplitude_anchor,
        gauge_weight,
        rho_target,
        rho_weight,
    )
    sol = least_squares(
        _residual,
        z0,
        jac=_jacobian,
        args=solver_args,
        method="trf",
        tr_solver=tr_solver,
        x_scale="jac",
        xtol=1e-14,
        ftol=1e-14,
        gtol=1e-14,
        max_nfev=max_nfev,
    )
    coeffs, omega2 = _unpack(sol.x, n1, n2)
    n_res = m1 * m2 * _N_STATE
    residual_rms = float(np.sqrt(np.sum(sol.fun[:n_res] ** 2) / n_res))
    amp = _transverse_amplitude(coeffs, n2)
    rot = omega2 / omega1

    result = CRNBPTorusVariationalResult(
        system=system,
        coeffs=coeffs,
        omega1=omega1,
        omega2=omega2,
        rotation_number=rot,
        rho_strob=omega2 * period,
        period=period,
        n1=n1,
        n2=n2,
        m1=m1,
        m2=m2,
        period_multiple=period_multiple,
        transverse_amplitude=amp,
        residual_rms=residual_rms,
        closure_residual=float("nan"),
        converged=False,
        n_iter=int(sol.nfev),
        notes=notes,
    )
    closure = _independent_closure(result, closure_dt_frac, n_closure_samples)
    converged = (residual_rms < tol) and (closure < closure_tol)
    result = replace(result, closure_residual=closure, converged=converged)
    io_mu = system.perturbers[0].mu if len(system.perturbers) >= 1 else 0.0
    gan_mu = system.perturbers[-1].mu
    log_outcome(
        solver="variational_crnbp_torus.correct_crnbp_torus_pseudospectral",
        inputs={
            "mu": float(mu),
            "mu_io": float(io_mu),
            "mu_gan": float(gan_mu),
            "n1": int(n1),
            "n2": int(n2),
            "period_multiple": int(period_multiple),
            "amplitude_anchor": float(amplitude_anchor),
        },
        outcome={
            "converged": bool(converged),
            "residual_rms": residual_rms,
            "closure_residual": closure,
            "omega2": float(omega2),
            "rotation_number": float(rot),
            "rho_strob": float(omega2 * period),
            "transverse_amplitude": float(amp),
        },
        meta={"model": "crnbp"},
    )
    return result


def _independent_closure(
    result: CRNBPTorusVariationalResult, dt_frac: float, n_samples: int
) -> float:
    """Short-time flow-consistency check (independent of the algebraic residual).

    Propagates through the FULL, coupling-term-included
    :func:`cyclerfinder.core.crnbp.crnbp_eom` -- NOT the simplified
    coupling-omitted grid RHS the corrector's residual uses -- so this is also
    the sharpest available runtime confirmation that omitting the coupling
    term from the algebraic residual was safe (`#717`'s zero-net-contribution
    proof). Identical structure to `#690`'s ``_independent_closure``.
    """
    dt = dt_frac * result.period
    rng = np.random.default_rng(0xC0FFEE)
    max_err = 0.0
    for _ in range(n_samples):
        th1 = float(rng.uniform(0, 2 * np.pi))
        th2 = float(rng.uniform(0, 2 * np.pi))
        u0 = evaluate_torus_state(result, th1, th2)
        s6 = np.array([u0[0], u0[1], 0.0, u0[2], u0[3], 0.0], dtype=np.float64)
        t0 = th1 / result.omega1
        sol = solve_ivp(
            crnbp.crnbp_eom,
            (t0, t0 + dt),
            s6,
            args=(result.system,),
            method="DOP853",
            rtol=1e-12,
            atol=1e-12,
        )
        if not sol.success:
            return float("inf")
        u_target = evaluate_torus_state(result, th1 + result.omega1 * dt, th2 + result.omega2 * dt)
        end = sol.y[:, -1]
        planar_end = np.array([end[0], end[1], end[3], end[4]], dtype=np.float64)
        max_err = max(max_err, float(np.linalg.norm(planar_end - u_target)))
    return max_err


# ---------------------------------------------------------------------------
# mu_Io = 0 seeding from #690's own converged CCR4BP torus, and continuation.
# ---------------------------------------------------------------------------


def crnbp_system_at_mu_io(
    ccr4bp_mu: float,
    mu_gan: float,
    a_gan: float,
    omega_gan: float,
    *,
    mu_io: float,
    a_io: float,
    omega_io: float,
    theta_io0: float = 0.0,
    theta_gan0: float = 0.0,
) -> crnbp.CRNBPSystem:
    """Build a ``(io, ganymede)``-ordered :class:`crnbp.CRNBPSystem` from a
    CCR4BP system's own ``(mu, mu_gan, a_gan, omega_gan)`` plus an Io
    perturber. ``mu_io = 0.0`` reproduces the CCR4BP system exactly (`#717`
    Gate 1)."""
    io = crnbp.CRNBPPerturber(mu=mu_io, a=a_io, omega=omega_io, theta0=theta_io0)
    gan = crnbp.CRNBPPerturber(mu=mu_gan, a=a_gan, omega=omega_gan, theta0=theta_gan0)
    return crnbp.CRNBPSystem(mu=ccr4bp_mu, perturbers=(io, gan))


def discover_crnbp_torus_from_ccr4bp_seed(
    ccr4bp_result: CCR4BPTorusVariationalResult,
    *,
    mu_io: float,
    a_io: float,
    omega_io: float,
    theta_io0: float = 0.0,
    rho_weight: float = 100.0,
    gauge_weight: float = 30.0,
    tr_solver: Literal["exact", "lsmr"] = "exact",
    tol: float = 1e-6,
    closure_tol: float = 1e-4,
    max_nfev: int = 600,
    closure_dt_frac: float = 0.02,
    notes: str = "",
) -> CRNBPTorusVariationalResult:
    """Seed an N=5 CRNBP torus corrector from `#690`'s own converged
    ``CCR4BPTorusVariationalResult`` (``ccr4bp_result``).

    At ``mu_io = 0.0`` this reproduces the CCR4BP torus exactly (Tier-0 gate);
    at ``mu_io > 0`` it is the FIRST corrector solve of the N=5 continuation
    (normally called via :func:`continue_crnbp_torus_mu_io` instead, which
    walks ``mu_io`` up gradually from this ``mu_io=0`` anchor).
    """
    base = ccr4bp_result.system
    system = crnbp_system_at_mu_io(
        base.mu,
        base.mu_gan,
        base.a_gan,
        base.omega_gan,
        mu_io=mu_io,
        a_io=a_io,
        omega_io=omega_io,
        theta_io0=theta_io0,
        theta_gan0=base.theta_gan0,
    )
    return correct_crnbp_torus_pseudospectral(
        system,
        ccr4bp_result.coeffs,
        ccr4bp_result.omega2,
        n1=ccr4bp_result.n1,
        n2=ccr4bp_result.n2,
        m1=ccr4bp_result.m1,
        m2=ccr4bp_result.m2,
        period_multiple=ccr4bp_result.period_multiple,
        amplitude_anchor=ccr4bp_result.transverse_amplitude,
        rho_target=ccr4bp_result.rotation_number,
        rho_weight=rho_weight,
        gauge_weight=gauge_weight,
        tr_solver=tr_solver,
        tol=tol,
        closure_tol=closure_tol,
        max_nfev=max_nfev,
        closure_dt_frac=closure_dt_frac,
        notes=notes or "seeded_from_ccr4bp_mu_io_zero",
    )


def continue_crnbp_torus_mu_io(
    result: CRNBPTorusVariationalResult,
    target_system: crnbp.CRNBPSystem,
    *,
    n_steps: int = 8,
    rho_weight: float = 1.0,
    gauge_weight: float = 1.0,
    tr_solver: Literal["exact", "lsmr"] = "exact",
    tol: float = 1e-6,
    closure_tol: float = 1e-4,
    max_nfev: int = 400,
    closure_dt_frac: float = 0.02,
    divergence_factor: float = 1.0e3,
) -> list[CRNBPTorusVariationalResult]:
    """Homotopy in Io's mass from ``result.system.perturbers[0].mu`` to
    ``target_system.perturbers[0].mu`` (nominally 0 -> the Laplace-projected
    physical value, ~4.7e-5), holding Ganymede's ``(mu, a, omega, theta0)``
    and Io's own ``(a, omega, theta0)`` fixed at the target's.

    Mirrors
    :func:`cyclerfinder.search.variational_ccr4bp_torus.continue_ccr4bp_torus_mass`
    exactly, one level up (Io's mass instead of Ganymede's). Stops early only
    on genuine DIVERGENCE (non-finite residual or one growing past
    ``divergence_factor`` times the seed's), not on the strict ``converged``
    flag -- the honest per-step residual is what should be reported.
    """
    io0 = result.system.perturbers[0]
    gan_t = target_system.perturbers[-1]
    io_t = target_system.perturbers[0]
    steps: list[CRNBPTorusVariationalResult] = []
    current = result
    floor = max(result.residual_rms, 1.0e-6)
    mu_ios = np.linspace(io0.mu, io_t.mu, n_steps + 1)[1:]
    for mi in mu_ios:
        io_step = replace(io_t, mu=float(mi))
        sys_step = crnbp.CRNBPSystem(mu=target_system.mu, perturbers=(io_step, gan_t))
        nxt = correct_crnbp_torus_pseudospectral(
            sys_step,
            current.coeffs,
            current.omega2,
            n1=current.n1,
            n2=current.n2,
            m1=current.m1,
            m2=current.m2,
            period_multiple=current.period_multiple,
            amplitude_anchor=current.transverse_amplitude,
            rho_target=current.rotation_number,
            rho_weight=rho_weight,
            gauge_weight=gauge_weight,
            tr_solver=tr_solver,
            tol=tol,
            closure_tol=closure_tol,
            max_nfev=max_nfev,
            closure_dt_frac=closure_dt_frac,
            notes=f"mu_io_continuation_mu_io={mi:.6e}",
        )
        steps.append(nxt)
        current = nxt
        if not np.isfinite(nxt.residual_rms) or nxt.residual_rms > divergence_factor * floor:
            break
    return steps
