"""§14 V1 frozen-gate evidence for #365 Russell-Ocampo 2003 Tables 5-8 wave.

This module is a FROZEN-GATE wrapper asserting that the V1 verdict JSONLs on
disk (produced by ``scripts/run_365_russell_ocampo_v1.py``) say what the
catalogue rows claim. It does NOT recompute the corrector: the four candidate
verdicts were generated by the closer_sweep_v1 substrate (a documented
campaign) and are frozen into project-output JSONLs.

Russell-Ocampo 2003 (AAS-03-145) Tables 5-8 publish per-encounter Δv vectors
for FOUR cyclers — the only rows in that paper with reproducible per-encounter
state in the circular-coplanar model (Mars period 1.875 yr, Earth 1 yr, zero-
SOI flyby). The §14 V1 like-for-like reproduction asks: does our circular-
coplanar free-return corrector, seeded from the row's SOURCED
``(aphelion_au, transit_em_days)`` and run at the best phase, EMERGE per-body
V_inf magnitudes within 0.5 km/s of the SOURCED Russell 2004 Table 3.4
anchor AND clear the §14 V1 mechanics gate (closed, V_inf-continuous single
ellipse)?

VERDICT — 2026-06-17 driver run (commit pre-#365):

* ``russell-ocampo-2.5.1+0`` (Cycler-2-5-1-3, Table 5)  — **PASS** (V0→V1).
  Derived E/M V_inf = 7.895/9.942 km/s vs sourced 7.8/9.9 (|ΔE|=0.10,
  |ΔM|=0.04, both < 0.5). Single ellipse closes, V_inf-continuous.
* ``russell-ocampo-3.1.2+1`` (Cycler-3-1-2-11, Table 6) — **FAIL** CLOSE-NOT-V1.
  V_inf matches (3.42/4.62 vs 3.4/4.6, both < 0.5) but the single ellipse does
  not close to Earth — multi-arc, V_inf continuity broken at the Mars flyby.
* ``russell-ocampo-4.3.1-5`` (Cycler-4-3-1-20, Table 7) — **FAIL** NO-CLOSE.
  Aphelion 1.505 AU just inside Mars sma 1.52 AU; single radial-crossing ellipse
  cannot reach Mars at the seeded geometry (Russell §3.8: "the cycler doesn't
  quite reach Mars in the simplified model").
* ``russell-ocampo-4.5.2-2`` (Cycler-4-5-2-12, Table 8) — **FAIL** CLOSE-NOT-V1.
  V_inf matches (3.36/4.61 vs 3.4/4.6) but the corrector grazes the residual
  floor (max_res 0.103 > 0.1) and the V_inf-continuity gate rejects it as a
  multi-arc cycler.

HONEST NEGATIVES discipline (project memory ``feedback_orbit_closure_discipline``):
nothing here is tuned to force a pass. THREE of four candidates legitimately
fail the same-model §14 V1 gate — the multi-arc topology fundamentally cannot
be reproduced by a single free-return ellipse, exactly the limitation the
existing closer_sweep_v1 ``CLOSE_NOT_V1`` set already pins. The PASS row
2.5.1+0's single ellipse closes BECAUSE its 94-day Earth-Mars leg matches a
single radial-crossing solution — short-transit / high-V_inf cyclers are
single-ellipse-reachable; long-transit / multi-arc cyclers are not.

Sourced-golden discipline (``feedback_golden_tests_sourced_only``): the EXPECTED
side is the JSONL file itself, sourced from the closer_sweep_v1 driver output.
The PASS candidate's V_inf gate compares the EMERGED ``derived_vinf_kms``
against the SOURCED Russell 2004 Table 3.4 / Russell-Ocampo 2003 Table 4
anchor; no anchor side is computed by us.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
V1_FLOOR_KMS = 0.5  # spec §14 V1: same-model |Δvinf| < 0.5 km/s


def _load_verdict(row_id: str) -> dict[str, Any]:
    path = REPO_ROOT / "data" / f"{row_id}_v1_verdict.jsonl"
    assert path.exists(), f"frozen verdict file missing: {path}"
    with path.open() as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            return json.loads(line)  # type: ignore[no-any-return]
    raise AssertionError(f"verdict JSONL empty: {path}")


# ---------------------------------------------------------------------------
# PASS: russell-ocampo-2.5.1+0 (Cycler-2-5-1-3)
# ---------------------------------------------------------------------------


def test_russell_ocampo_2_5_1_plus_0_v1_pass() -> None:
    """russell-ocampo-2.5.1+0 V1 promotion: closes + V_inf within 0.5 km/s."""
    row = _load_verdict("russell-ocampo-2.5.1+0")
    assert row["candidate_id"] == "russell-ocampo-2.5.1+0"
    assert row["paper_cycler"] == "Cycler-2-5-1-3"
    assert row["passes_v1"] is True, (
        f"V1 verdict reports passes_v1={row['passes_v1']!r} — registry entry "
        f"must be re-validated; fail_mode={row['fail_mode']!r}."
    )
    assert row["verdict"] == "PASS"
    assert row["corrector"]["converged"] is True
    assert row["v1_mechanics_passed"] is True
    assert row["vinf_continuous"] is True
    # Per-encounter V_inf gates (the §14 V1 floor).
    assert float(row["v1_floor_kms"]) == V1_FLOOR_KMS
    assert row["vinf_gate_E_passed"] is True
    assert row["vinf_gate_M_passed"] is True
    d_e = float(row["delta_vinf_kms"]["E"])
    d_m = float(row["delta_vinf_kms"]["M"])
    assert d_e <= V1_FLOOR_KMS, f"|ΔV_inf_E|={d_e:.4f} > {V1_FLOOR_KMS}"
    assert d_m <= V1_FLOOR_KMS, f"|ΔV_inf_M|={d_m:.4f} > {V1_FLOOR_KMS}"
    # Sanity: the sourced anchor in the catalogue row IS what the paper publishes.
    assert row["sourced_anchor_consistent_with_paper"] is True


# ---------------------------------------------------------------------------
# FAIL — honest negatives, stay V0
# ---------------------------------------------------------------------------


FAIL_CANDIDATES = [
    ("russell-ocampo-3.1.2+1", "Cycler-3-1-2-11", "CLOSE-NOT-V1"),
    ("russell-ocampo-4.3.1-5", "Cycler-4-3-1-20", "NO-CLOSE"),
    ("russell-ocampo-4.5.2-2", "Cycler-4-5-2-12", "CLOSE-NOT-V1"),
]


@pytest.mark.parametrize(("row_id", "paper_cycler", "fail_kind"), FAIL_CANDIDATES)
def test_russell_ocampo_v1_honest_negative(row_id: str, paper_cycler: str, fail_kind: str) -> None:
    """Honest-negative gate: these three multi-arc rows do NOT clear §14 V1
    via the single-ellipse corrector; they legitimately stay V0.

    Pinned so the discipline rule (math gives the verdict, not a tuned pass)
    cannot silently flip them into the promoted set. The catalogue row stays
    at V0 with the same fail mode the JSONL records.
    """
    row = _load_verdict(row_id)
    assert row["candidate_id"] == row_id
    assert row["paper_cycler"] == paper_cycler
    assert row["passes_v1"] is False, (
        f"V1 verdict reports passes_v1={row['passes_v1']!r} — the FAIL gate "
        "is itself the registry evidence; if this flips, re-validate."
    )
    assert row["verdict"] == "FAIL"
    assert fail_kind in row["fail_mode"], (
        f"expected fail_mode containing {fail_kind!r}, got {row['fail_mode']!r}"
    )
    # The sourced anchor still matches the paper — the FAIL is on the V1
    # mechanics side, not on a sourced-anchor inconsistency.
    assert row["sourced_anchor_consistent_with_paper"] is True
